### PR TITLE
#206

### PR DESCRIPTION
**Pull request by acournoyer1**
Tested by added a bunch of items to the menu, works.

### CODE REVIEW

**Comment by HaGuesto** [comment]
I review this one.

**Comment by HaGuesto** [comment]
I don't have the Safari mobile browser set up. So, it would take me a bit to review this one. Anyone else?

**Comment by bfirsh** [comment]
Clickable link to issue #206

**Comment by bfirsh** [comment]
I'll take a look

**Comment by acournoyer1** [comment]
Just realized, works on android but not on mobile safari, would need to just add position: relative to my lock class

**Comment by bfirsh** [comment]
img_3758

Hmm... this doesn't seem to fix a weird issue on iPhone 5/SE sized screens where the sign out button is just out of reach. The menu is not scrollable, I think because it's smaller than the viewport/100vh. You can scroll up to make the URL bar go away, but it keeps on popping back, making it very fiddling to click on the sign out link.

Maybe we could add a bunch of padding to the bottom of the menu. That might force it to be scrollable so you can scroll up enough to see the sign out link.

**Comment by bfirsh** [comment]
@acournoyer1 ah, ok! I'll merge this and give that a shot. :)

**Comment by bfirsh** [comment]
@acournoyer1 Hm - negative. Still doesn't work with position: relative.

**Pull request merged**
