### PR TITLE
Detaching business rules from within the signin component to the actions

### LINKED ISSUE #79: profile redux state needs an action for starting to fetch to set isFetching
When you sign out, isFetching is never set again.

### LINKED ISSUE #158: Refactor SignInForm to use a container component
## Problem

All the presentation and logic is muddled in the same file.

## Solution

Split it out into `SignInForm` and `SignInFormContainer`, using a property for the Formik submit handler. See the other containers components for examples of how this is done.

### PR DESCRIPTION
**Pull request by rubenspgcavalcante**
Added a containers directory and separated them by components and pages.
Maybe we can refactor this within modules or so 👍 

Closes #158 and closes #79

### CODE REVIEW

**Comment by bfirsh** [comment]
Awesome! Thank you! It looks like signing out doesn't work, though. When `onAuthStateChanged` fires with a null user should set `isEmpty` back to true and clear the profile, like in the previous action/reducer.

See also #79. Profile needs some similar actions to the ones you've created for user. :)

**Comment by rubenspgcavalcante** [comment]
Ok, I'll refactor and try to apply the same concept over the `profile`.
With the change moving the fetched info to another sub property, like info or data, we'll don't need the `isEmpty` anymore, as if user.data have a object is filled and if is null is empty 👍

**Comment by rubenspgcavalcante** [comment]
I mean, I didn't moved to the internal property, but will do on the next commits and with it fix the problem you pointed out 👍

**Comment by rubenspgcavalcante** [comment]
I'm going to refactor the `profile` now :)

**Comment by rubenspgcavalcante** [comment]
Ok @bfirsh , all finished!
You can review now :)

**Comment by bfirsh** [comment]
Thank you!

**Pull request merged**
