### PR TITLE
Added a "Password Reset" page (linked to from sign in page)

### PR DESCRIPTION
**Pull request by MichaelBurjack**
As per Issue #22

### CODE REVIEW

**Comment by HaGuesto** [comment]
I review this one.

**Comment by bfirsh** [comment]
Does it? Won't `firebase.auth().sendPasswordResetEmail()` validate it?

This is so great @MichaelBurjack - thank you!

**Comment by HaGuesto** [comment]
It only checks if there is an @ between strings at the moment.

**Comment by bfirsh** [comment]
Do you mean that we should validate whether the email exists in our database?

We probably don't actually want to do that, otherwise this is a vector to discovering whether somebody has signed up with that email, which could be used for various nefarious purposes. (Actually, I suppose the sign up form already exposes that data doesn't it. Hrm.)

Regardless, we can always add more validation later. LGTM, from me.

**Comment by MichaelBurjack** [comment]
Agreed that the better pattern is to silently fail (which admittedly this patch doesn't do well) to prevent someone using the "reset password" mechanism as a user account sniffing hook.

In terms of failing when the Firebase call fails, the failure is passed up to the `handleError()` method in `utils.js` which currently just emits a console message. This error handler is already used throughout the app, and I figured creating a better error handling framework was outside the scope of this ticket ;)

You can see the same issue by trying to log in with invalid credentials — the error is not yet properly handled there, either. Probably makes sense to update both/all authentication error conditions as a follow-up ticket.

**Comment by bfirsh** [comment]
:+1: That reminds me we should make an issue for that, thanks. :)

**Pull request merged**
