### PR TITLE
#106: replace CircularProgress with a custom boxwise Progress component

### PR DESCRIPTION
**Pull request by sfetiveau-ta**

### CODE REVIEW

**Comment by bfirsh** [comment]
@sfetiveau-ta Needs a rebase - sorry! Let me know if you don't have time to do it and we can sort it out. :)

**Comment by sfetiveau-ta** [comment]
I merged your master in my fork and resolved the conflict, it should be good to go

**Comment by bfirsh** [comment]
Brilliant, thank you!

**Comment by bfirsh** [comment]
superseded by #234

**Pull request closed without merging**
